# vim:ft=kitty
## name: ch-sledding
## blurb: Calvin & Hobbes sledding in winter — white snowy scene, darkened
## settings: padding=12 opacity=1.0 font_size=14.0
## bg_image: ~/.config/kitty/images/ch-sledding.jpg

foreground              #ffffff
background              #1a1a1a
selection_foreground    #1a1a1a
selection_background    #ffffff
cursor                  #ffffff
cursor_text_color       #1a1a1a
url_color               #1a8fff

active_border_color     #00ff00
inactive_border_color   #555555
bell_border_color       #ff5a00
visual_bell_color       none

color0  #000000
color8  #c0c0c0
color1  #cc0403
color9  #f2201f
color2  #19cb00
color10 #23fd00
color3  #cecb00
color11 #fffd00
color4  #0d73cc
color12 #1a8fff
color5  #cb1ed1
color13 #fd28ff
color6  #0dcdcd
color14 #14ffff
color7  #e0e0e0
color15 #ffffff
